[pytest]
console_output_style = short
addopts = -v --tb=short
testpaths = test_case
markers =
    login: login test cases
    busticket: busticket test cases
    ticket: ticket test cases
# 后续接 Allure 时，addopts 改为这个：-v --tb=short --alluredir=reports/allure-results --clean-alluredir