projectName=港版PC端登录自动化测试
    pythonVersion=3.8.5
    allureVersion=2.11.0
    baseUrl=https://www.testhopetrip.dabapiao.com/
    executionTime=2026-08-20 18:55:18
    author=Test_Team
    osName=Windows
    osVersion=10
    browserName=Chrome
    browserVersion=87.0.4280.88
    browserSize=1920x1080
    